// Auto-generated by Launch Kit — DO NOT EDIT.
#pragma once
#define CUSTOM_APP_CLOCK        1
#define CUSTOM_APP_FLIGHT       0
#define CUSTOM_APP_WEATHER      0
#define CUSTOM_APP_INTEL        0
#define CUSTOM_APP_SURVEILLANCE 0
#define CUSTOM_APP_SETTINGS     1
