// Auto-generated by Launch Kit — DO NOT EDIT.
#pragma once
#include "lvgl.h"
#define CUSTOM_HAS_MENU 1
#define CUSTOM_HAS_MENU_CURRENT 1
#define CUSTOM_MENU_CURRENT_X 233
#define CUSTOM_MENU_CURRENT_Y 233
#define CUSTOM_MENU_CURRENT_COLOR 0xFF3B30
#define CUSTOM_MENU_CURRENT_GLOW 0
#define CUSTOM_MENU_CURRENT_GLOWCOLOR 0x1DFF86
#define CUSTOM_MENU_CURRENT_FMT "{name}"
#define CUSTOM_MENU_CURRENT_ALIGN 1
#define CUSTOM_HAS_MENU_PREV 0
#define CUSTOM_HAS_MENU_NEXT 0
#ifdef __cplusplus
extern "C" {
#endif
extern const lv_font_t custom_menu_font1;
#ifdef __cplusplus
}
#endif
#define CUSTOM_MENU_CURRENT_FONT (&custom_menu_font1)
#define CUSTOM_MENU_PREV_FONT (&lv_font_montserrat_16)
#define CUSTOM_MENU_NEXT_FONT (&lv_font_montserrat_16)
