// Auto-generated by Launch Kit — DO NOT EDIT.
// Pushed from the clock editor. The visual layers (plate/overlay/hands) live in
// custom_plate.h / custom_overlay.h / custom_hands.h; this carries only the bits
// the compositor still draws itself (the live text and a fallback background).
#pragma once
#include "custom_clock_types.h"

static const CustomClockDesign CUSTOM_CLOCK = {
    /* active */ true,
    /* bg     */ 0x000000,
    /* text1  */ { true, 233, 124, 48, 0x303030, "%I:%M" },
    /* text2  */ { true, 233, 164, 16, 0x707070, "%a, %d %b" },
};
